inherit_from:
  - .rubocop_todo.yml
  - .rubocop_dnsimple.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'

# This rule conflicts with our specs codebase using Ruby 2.x and 3.x
Lint/NonDeterministicRequireOrder:
  Enabled: false
