inherit_from:
  - .rubocop_todo.yml
  - .rubocop_dnsimple.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'

# [codesmell]
# It's irrelevant here, but it could be a code smell.
# Hence keep it disabled, but don't include it in the DNSimple suite.
Lint/Loop:
  Enabled: false

# This rule conflicts with our specs codebase using Ruby 2.x and 3.x
Lint/NonDeterministicRequireOrder:
  Enabled: false
